In [1]:
import pandas as pd
df = pd.read_csv('/home/lizhi/projects/covid19/rural_urban_codes_2013.csv')

In [2]:
import numpy as np

from bokeh.io import curdoc, show
from bokeh.models import ColumnDataSource, Grid, LinearAxis, Plot, Quad

N = 9
x = np.linspace(-2, 2, N)
y = x**2

source = ColumnDataSource(dict(
        left=x,
        top=y,
        right=x-x**3/10 + 0.3,
        bottom=y-x**2/10 + 0.5,
    )
)

plot = Plot(
    title=None, plot_width=300, plot_height=300,
    min_border=0, toolbar_location=None)

glyph = Quad(left="left", right="right", top="top", bottom="bottom", fill_color="#b3de69")
plot.add_glyph(source, glyph)

xaxis = LinearAxis()
plot.add_layout(xaxis, 'below')

yaxis = LinearAxis()
plot.add_layout(yaxis, 'left')

plot.add_layout(Grid(dimension=0, ticker=xaxis.ticker))
plot.add_layout(Grid(dimension=1, ticker=yaxis.ticker))

curdoc().add_root(plot)

show(plot)

In [85]:
df

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
0,1001,AL,Autauga County,54571,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
1,1003,AL,Baldwin County,182265,3,Metro - Counties in metro areas of fewer than ...,NaN
2,1005,AL,Barbour County,27457,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
3,1007,AL,Bibb County,22915,1,Metro - Counties in metro areas of 1 million p...,NaN
4,1009,AL,Blount County,57322,1,Metro - Counties in metro areas of 1 million p...,NaN
...,...,...,...,...,...,...,...
3216,72145,PR,Vega Baja Municipio,59662,1,Metro - Counties in metro areas of 1 million p...,NaN
3217,72147,PR,Vieques Municipio,9301,7,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
3218,72149,PR,Villalba Municipio,26073,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
3219,72151,PR,Yabucoa Municipio,37941,1,Metro - Counties in metro areas of 1 million p...,NaN
3220,72153,PR,Yauco Municipio,42043,2,"Metro - Counties in metro areas of 250,000 to ...",NaN

In [86]:
df.shape

(3221, 7)

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3221 entries, 0 to 3220
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FIPS                        3221 non-null   int64
 1   State                       3221 non-null   object
 2   County_Name                 3221 non-null   object
 3   Population_2010             3221 non-null   int64
 4   RUCC_2013                   3221 non-null   int64
 5   Description                 3221 non-null   object
 6   orignal_population_2010_wa  39 non-null     float64
dtypes: float64(1), int64(3), object(3)
memory usage: 176.3+ KB

In [88]:
pd.set_option('display.max_columns',7)

In [89]:
schema_df = pd.read_csv('/home/lizhi/projects/covid19/rural_urban_codes_2013.csv')

In [90]:
schema_df

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
0,1001,AL,Autauga County,54571,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
1,1003,AL,Baldwin County,182265,3,Metro - Counties in metro areas of fewer than ...,NaN
2,1005,AL,Barbour County,27457,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
3,1007,AL,Bibb County,22915,1,Metro - Counties in metro areas of 1 million p...,NaN
4,1009,AL,Blount County,57322,1,Metro - Counties in metro areas of 1 million p...,NaN
...,...,...,...,...,...,...,...
3216,72145,PR,Vega Baja Municipio,59662,1,Metro - Counties in metro areas of 1 million p...,NaN
3217,72147,PR,Vieques Municipio,9301,7,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
3218,72149,PR,Villalba Municipio,26073,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
3219,72151,PR,Yabucoa Municipio,37941,1,Metro - Counties in metro areas of 1 million p...,NaN
3220,72153,PR,Yauco Municipio,42043,2,"Metro - Counties in metro areas of 250,000 to ...",NaN

In [91]:
df.head(10)

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
0,1001,AL,Autauga County,54571,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
1,1003,AL,Baldwin County,182265,3,Metro - Counties in metro areas of fewer than ...,NaN
2,1005,AL,Barbour County,27457,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
3,1007,AL,Bibb County,22915,1,Metro - Counties in metro areas of 1 million p...,NaN
4,1009,AL,Blount County,57322,1,Metro - Counties in metro areas of 1 million p...,NaN
5,1011,AL,Bullock County,10914,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
6,1013,AL,Butler County,20947,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
7,1015,AL,Calhoun County,118572,3,Metro - Counties in metro areas of fewer than ...,NaN
8,1017,AL,Chambers County,34215,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
9,1019,AL,Cherokee County,25989,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN

In [92]:
df.count()

FIPS                          3221
State                         3221
County_Name                   3221
Population_2010               3221
RUCC_2013                     3221
Description                   3221
orignal_population_2010_wa      39
dtype: int64

In [93]:
df['FIPS']

0        1001
1        1003
2        1005
3        1007
4        1009
        ...
3216    72145
3217    72147
3218    72149
3219    72151
3220    72153
Name: FIPS, Length: 3221, dtype: int64

In [94]:
df[['FIPS','County_Name']]

       FIPS          County_Name
0      1001       Autauga County
1      1003       Baldwin County
2      1005       Barbour County
3      1007          Bibb County
4      1009        Blount County
...     ...                  ...
3216  72145  Vega Baja Municipio
3217  72147    Vieques Municipio
3218  72149   Villalba Municipio
3219  72151    Yabucoa Municipio
3220  72153      Yauco Municipio

[3221 rows x 2 columns]

In [95]:
type(df[['FIPS','County_Name']])

pandas.core.frame.DataFrame

In [96]:
df.columns

Index(['FIPS', 'State', 'County_Name', 'Population_2010', 'RUCC_2013',
       'Description', 'orignal_population_2010_wa'],
      dtype='object')

In [97]:
df.iloc[0]

FIPS                                                                       1001
State                                                                        AL
County_Name                                                      Autauga County
Population_2010                                                           54571
RUCC_2013                                                                     2
Description                   Metro - Counties in metro areas of 250,000 to ...
orignal_population_2010_wa                                                  NaN
Name: 0, dtype: object

In [98]:
df.iloc[4]

FIPS                                                                       1009
State                                                                        AL
County_Name                                                       Blount County
Population_2010                                                           57322
RUCC_2013                                                                     1
Description                   Metro - Counties in metro areas of 1 million p...
orignal_population_2010_wa                                                  NaN
Name: 4, dtype: object

In [99]:
df.iloc[2,5]

'Nonmetro - Urban population of 2,500 to 19,999, adjacent to a metro area                                                                                                                                '

In [100]:
df.iloc[[1,2]]

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
1,1003,AL,Baldwin County,182265,3,Metro - Counties in metro areas of fewer than ...,NaN
2,1005,AL,Barbour County,27457,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN

In [101]:
df.iloc[[1,2],5]

1    Metro - Counties in metro areas of fewer than ...
2    Nonmetro - Urban population of 2,500 to 19,999...
Name: Description, dtype: object

In [102]:
df.iloc[[1],[2,3,4,5]]

,County_Name,Population_2010,RUCC_2013,Description
1,Baldwin County,182265,3,Metro - Counties in metro areas of fewer than ...

In [103]:
df.loc[[2,5]]

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
2,1005,AL,Barbour County,27457,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
5,1011,AL,Bullock County,10914,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN

In [104]:
df.loc[[2,5],'Description']

2    Nonmetro - Urban population of 2,500 to 19,999...
5    Nonmetro - Urban population of 2,500 to 19,999...
Name: Description, dtype: object

In [105]:
df['State'].value_counts()

TX    254
GA    159
VA    134
KY    120
MO    115
KS    105
IL    102
NC    100
IA     99
TN     95
NE     93
IN     92
OH     88
MN     87
MI     83
MS     82
PR     78
OK     77
AR     75
WI     72
PA     67
AL     67
FL     67
SD     66
LA     64
CO     64
NY     62
CA     58
MT     56
WV     55
ND     53
SC     46
ID     44
WA     39
OR     36
NM     33
AK     29
UT     29
MD     24
WY     23
NJ     21
NV     17
ME     16
AZ     15
VT     14
MA     14
NH     10
CT      8
RI      5
HI      5
DE      3
DC      1
Name: State, dtype: int64

In [106]:
df.set_index('State')

,FIPS,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
State,,,,,,
AL,1001,Autauga County,54571,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
AL,1003,Baldwin County,182265,3,Metro - Counties in metro areas of fewer than ...,NaN
AL,1005,Barbour County,27457,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
AL,1007,Bibb County,22915,1,Metro - Counties in metro areas of 1 million p...,NaN
AL,1009,Blount County,57322,1,Metro - Counties in metro areas of 1 million p...,NaN
...,...,...,...,...,...,...
PR,72145,Vega Baja Municipio,59662,1,Metro - Counties in metro areas of 1 million p...,NaN
PR,72147,Vieques Municipio,9301,7,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
PR,72149,Villalba Municipio,26073,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
PR,72151,Yabucoa Municipio,37941,1,Metro - Counties in metro areas of 1 million p...,NaN
PR,72153,Yauco Municipio,42043,2,"Metro - Counties in metro areas of 250,000 to ...",NaN

In [107]:
df.sort_index(ascending=True )

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
0,1001,AL,Autauga County,54571,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
1,1003,AL,Baldwin County,182265,3,Metro - Counties in metro areas of fewer than ...,NaN
2,1005,AL,Barbour County,27457,6,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
3,1007,AL,Bibb County,22915,1,Metro - Counties in metro areas of 1 million p...,NaN
4,1009,AL,Blount County,57322,1,Metro - Counties in metro areas of 1 million p...,NaN
...,...,...,...,...,...,...,...
3216,72145,PR,Vega Baja Municipio,59662,1,Metro - Counties in metro areas of 1 million p...,NaN
3217,72147,PR,Vieques Municipio,9301,7,"Nonmetro - Urban population of 2,500 to 19,999...",NaN
3218,72149,PR,Villalba Municipio,26073,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
3219,72151,PR,Yabucoa Municipio,37941,1,Metro - Counties in metro areas of 1 million p...,NaN
3220,72153,PR,Yauco Municipio,42043,2,"Metro - Counties in metro areas of 250,000 to ...",NaN

In [108]:
df.index

RangeIndex(start=0, stop=3221, step=1)

In [109]:
filt = (df['State'] == 'WA')

In [111]:
df[filt]

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
2954,53001,WA,Adams County,18728,6,"Nonmetro - Urban population of 2,500 to 19,999...",18728.0
2955,53003,WA,Asotin County,21623,3,Metro - Counties in metro areas of fewer than ...,21623.0
2956,53005,WA,Benton County,201800,2,"Metro - Counties in metro areas of 250,000 to ...",175177.0
2957,53007,WA,Chelan County,78420,3,Metro - Counties in metro areas of fewer than ...,72453.0
2958,53009,WA,Clallam County,76010,5,"Nonmetro - Urban population of 20,000 or more,...",71404.0
2959,53011,WA,Clark County,488500,1,Metro - Counties in metro areas of 1 million p...,425363.0
2960,53013,WA,Columbia County,4078,3,Metro - Counties in metro areas of fewer than ...,4078.0
2961,53015,WA,Cowlitz County,108950,3,Metro - Counties in metro areas of fewer than ...,102410.0
2962,53017,WA,Douglas County,42820,3,Metro - Counties in metro areas of fewer than ...,38431.0
2963,53019,WA,Ferry County,7551,9,"Nonmetro - Completely rural or less than 2,500...",7551.0
2964,53021,WA,Franklin County,94680,2,"Metro - Counties in metro areas of 250,000 to ...",78163.0
2965,53023,WA,Garfield County,2266,8,"Nonmetro - Completely rural or less than 2,500...",2266.0
2966,53025,WA,Grant County,98740,5,"Nonmetro - Urban population of 20,000 or more,...",89120.0
2967,53027,WA,Grays Harbor County,74160,4,"Nonmetro - Urban population of 20,000 or more,...",72797.0
2968,53029,WA,Island County,84820,4,"Nonmetro - Urban population of 20,000 or more,...",78506.0
2969,53031,WA,Jefferson County,31900,6,"Nonmetro - Urban population of 2,500 to 19,999...",29872.0
2970,53033,WA,King County,2226300,1,Metro - Counties in metro areas of 1 million p...,1931249.0
2971,53035,WA,Kitsap County,270100,2,"Metro - Counties in metro areas of 250,000 to ...",251133.0
2972,53037,WA,Kittitas County,46570,4,"Nonmetro - Urban population of 20,000 or more,...",40915.0
2973,53039,WA,Klickitat County,22430,6,"Nonmetro - Urban population of 2,500 to 19,999...",20318.0
2974,53041,WA,Lewis County,79480,4,"Nonmetro - Urban population of 20,000 or more,...",75455.0
2975,53043,WA,Lincoln County,10570,8,"Nonmetro - Completely rural or less than 2,500...",10570.0
2976,53045,WA,Mason County,64980,4,"Nonmetro - Urban population of 20,000 or more,...",60699.0
2977,53047,WA,Okanogan County,42730,6,"Nonmetro - Urban population of 2,500 to 19,999...",41120.0
2978,53049,WA,Pacific County,21640,7,"Nonmetro - Urban population of 2,500 to 19,999...",20920.0
2979,53051,WA,Pend Oreille County,13001,2,"Metro - Counties in metro areas of 250,000 to ...",13001.0
2980,53053,WA,Pierce County,888300,1,Metro - Counties in metro areas of 1 million p...,795225.0
2981,53055,WA,San Juan County,17150,9,"Nonmetro - Completely rural or less than 2,500...",15769.0
2982,53057,WA,Skagit County,129200,3,Metro - Counties in metro areas of fewer than ...,116901.0
2983,53059,WA,Skamania County,11066,1,Metro - Counties in metro areas of 1 million p...,11066.0
2984,53061,WA,Snohomish County,818700,1,Metro - Counties in metro areas of 1 million p...,713335.0
2985,53063,WA,Spokane County,515250,2,"Metro - Counties in metro areas of 250,000 to ...",471221.0
2986,53065,WA,Stevens County,45570,2,"Metro - Counties in metro areas of 250,000 to ...",43531.0
2987,53067,WA,Thurston County,285800,2,"Metro - Counties in metro areas of 250,000 to ...",252264.0
2988,53069,WA,Wahkiakum County,4190,8,"Nonmetro - Completely rural or less than 2,500...",3978.0
2989,53071,WA,Walla Walla County,62200,3,Metro - Counties in metro areas of fewer than ...,58781.0
2990,53073,WA,Whatcom County,225300,3,Metro - Counties in metro areas of fewer than ...,201140.0
2991,53075,WA,Whitman County,44776,4,"Nonmetro - Urban population of 20,000 or more,...",44776.0
2992,53077,WA,Yakima County,255950,3,Metro - Counties in metro areas of fewer than ...,243231.0

In [115]:
df.loc[filt,'Population_2010']

2954      18728
2955      21623
2956     201800
2957      78420
2958      76010
2959     488500
2960       4078
2961     108950
2962      42820
2963       7551
2964      94680
2965       2266
2966      98740
2967      74160
2968      84820
2969      31900
2970    2226300
2971     270100
2972      46570
2973      22430
2974      79480
2975      10570
2976      64980
2977      42730
2978      21640
2979      13001
2980     888300
2981      17150
2982     129200
2983      11066
2984     818700
2985     515250
2986      45570
2987     285800
2988       4190
2989      62200
2990     225300
2991      44776
2992     255950
Name: Population_2010, dtype: int64

In [118]:
df.loc[filt,'Population_2010']

2954      18728
2955      21623
2956     201800
2957      78420
2958      76010
2959     488500
2960       4078
2961     108950
2962      42820
2963       7551
2964      94680
2965       2266
2966      98740
2967      74160
2968      84820
2969      31900
2970    2226300
2971     270100
2972      46570
2973      22430
2974      79480
2975      10570
2976      64980
2977      42730
2978      21640
2979      13001
2980     888300
2981      17150
2982     129200
2983      11066
2984     818700
2985     515250
2986      45570
2987     285800
2988       4190
2989      62200
2990     225300
2991      44776
2992     255950
Name: Population_2010, dtype: int64

In [119]:
population_100k = df['Population_2010']>=100000

In [128]:
df.loc[filt & population_100k & df['RUCC_2013'] == 3]

Empty DataFrame
Columns: [FIPS, State, County_Name, Population_2010, RUCC_2013, Description, orignal_population_2010_wa]
Index: []

In [124]:
df.loc[population_100k]

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
1,1003,AL,Baldwin County,182265,3,Metro - Counties in metro areas of fewer than ...,NaN
7,1015,AL,Calhoun County,118572,3,Metro - Counties in metro areas of fewer than ...,NaN
27,1055,AL,Etowah County,104430,3,Metro - Counties in metro areas of fewer than ...,NaN
34,1069,AL,Houston County,101547,3,Metro - Counties in metro areas of fewer than ...,NaN
36,1073,AL,Jefferson County,658466,1,Metro - Counties in metro areas of 1 million p...,NaN
...,...,...,...,...,...,...,...
3153,72021,PR,Bayamon Municipio,208116,1,Metro - Counties in metro areas of 1 million p...,NaN
3155,72025,PR,Caguas Municipio,142893,1,Metro - Counties in metro areas of 1 million p...,NaN
3158,72031,PR,Carolina Municipio,176762,1,Metro - Counties in metro areas of 1 million p...,NaN
3200,72113,PR,Ponce Municipio,166327,2,"Metro - Counties in metro areas of 250,000 to ...",NaN
3207,72127,PR,San Juan Municipio,395326,1,Metro - Counties in metro areas of 1 million p...,NaN

In [131]:
df.loc[filt & population_100k]

,FIPS,State,County_Name,Population_2010,RUCC_2013,Description,orignal_population_2010_wa
2956,53005,WA,Benton County,201800,2,"Metro - Counties in metro areas of 250,000 to ...",175177.0
2959,53011,WA,Clark County,488500,1,Metro - Counties in metro areas of 1 million p...,425363.0
2961,53015,WA,Cowlitz County,108950,3,Metro - Counties in metro areas of fewer than ...,102410.0
2970,53033,WA,King County,2226300,1,Metro - Counties in metro areas of 1 million p...,1931249.0
2971,53035,WA,Kitsap County,270100,2,"Metro - Counties in metro areas of 250,000 to ...",251133.0
2980,53053,WA,Pierce County,888300,1,Metro - Counties in metro areas of 1 million p...,795225.0
2982,53057,WA,Skagit County,129200,3,Metro - Counties in metro areas of fewer than ...,116901.0
2984,53061,WA,Snohomish County,818700,1,Metro - Counties in metro areas of 1 million p...,713335.0
2985,53063,WA,Spokane County,515250,2,"Metro - Counties in metro areas of 250,000 to ...",471221.0
2987,53067,WA,Thurston County,285800,2,"Metro - Counties in metro areas of 250,000 to ...",252264.0
2990,53073,WA,Whatcom County,225300,3,Metro - Counties in metro areas of fewer than ...,201140.0
2992,53077,WA,Yakima County,255950,3,Metro - Counties in metro areas of fewer than ...,243231.0

In [132]:
df.describe()

               FIPS  Population_2010    RUCC_2013  orignal_population_2010_wa
count   3221.000000     3.221000e+03  3221.000000                3.900000e+01
mean   31399.890407     9.726268e+04     4.936976                1.724241e+05
std    16293.347468     3.100799e+05     2.724413                3.424514e+05
min     1001.000000     8.200000e+01     1.000000                2.266000e+03
25%    19033.000000     1.131000e+04     2.000000                2.061900e+04
50%    30025.000000     2.607600e+04     6.000000                6.069900e+04
75%    46109.000000     6.588000e+04     7.000000                1.460390e+05
max    72153.000000     9.818605e+06     9.000000                1.931249e+06

In [1]:
Trying to find if the legend label can be shared in multiple plots.
from bokeh.io import show
from bokeh.plotting import figure
from bokeh.models import LegendItem, Legend
from numpy.random import random, choice
from bokeh.layouts import gridplot
from webcolors import html4_names_to_hex

del html4_names_to_hex['white']
palette = list(html4_names_to_hex.keys())

fig_list = [figure(plot_width=300,plot_height=300) for i in range(4)]

renderer_list = []
color_list = []
for fig in fig_list:
    for i in range(5):
        color = choice(palette)
        renderer = fig.line(range(10),random(10),line_width=2,color=color)
        renderer_list += [renderer]
        color_list += [color]

# Lines with the same color will share a same legend item
legend_items = [LegendItem(label=color,renderers=[renderer for renderer in renderer_list if renderer.glyph.line_color==color]) for color in set(color_list)]

## Use a dummy figure for the LEGEND
dum_fig = figure(plot_width=300,plot_height=600,outline_line_alpha=0,toolbar_location=None)
# set the components of the figure invisible
for fig_component in [dum_fig.grid[0],dum_fig.ygrid[0],dum_fig.xaxis[0],dum_fig.yaxis[0]]:
    fig_component.visible = False
# The glyphs referred by the legend need to be present in the figure that holds the legend, so we must add them to the figure renderers
dum_fig.renderers += renderer_list
# set the figure range outside of the range of all glyphs
dum_fig.x_range.end = 1005
dum_fig.x_range.start = 1000
# add the legend
dum_fig.add_layout( Legend(click_policy='hide',location='top_left',border_line_alpha=0,items=legend_items) )

figrid = gridplot(fig_list,ncols=2,toolbar_location='left')
final = gridplot([[figrid,dum_fig]],toolbar_location=None)
show(final)

ModuleNotFoundError: No module named 'webcolors'

In [2]:
import l_common as c
import itertools as it
import operator
import datetime

sql_str = """
    select date, state, county,
    cases-lag(cases, 1) over(partition by county order by date) as daily_cases,
    deaths-lag(deaths,1) over(partition by county order by date) as daily_deaths
    from covid19.us_counties
    where state in ('Washington', 'Alabama')
    and date > date_sub(current_date(), interval 1 MONTH)
    and lower(substr(county,1,1)) in ('a','k')
    order by state, county, date"""

col_names = ['date', 'state', 'county', 'daily_cases', 'daily_deaths']

df = c.dataframe_from_sql(col_names, sql_str)
# source = ColumnDataSource(df)

# c.all_counties_graph('Washington', df)
# c.all_counties_graph('Alabama', df)
c.list_of_state_graph(["Alabama", "Washington"], df)